### ISSUE TITLE
Notification color not changing

### ISSUE THREAD

**Issue by DarkWarden85** [Grumblezz/Home-Assistant-Notify-Mobile-Companion-App-Devices#1]
Hi,

Thanks for this awesome script. Everything seems to work, except for the icon color.
I can select the colors just fine but the received notification on my phone always has the standard blue home assistant icon color.
Could it be that colors are broken in this script?

I am currently using a Pixel 6 running Android 13 with all the latest updates.

**Comment by Grumblezz** [comment]
Hi [DarkWarden85](https://github.com/DarkWarden85) Let me have a look at it. I have tested it before and it has worked...

**Comment by Grumblezz** [comment]
Fixed! The [rgb color object selector](https://www.home-assistant.io/docs/blueprint/selectors/#rgb-color-selector) spits it out as list with r,g and b `[255,0,0]`. This conflicts with the [ notification-color documentation](https://companion.home-assistant.io/docs/notifications/notifications-basic#notification-color), which requires HEX values. It has now been fixed. Thanks to https://github.com/velijv/home-assistant-color-helpers#rgb-to-hex

**Comment by DarkWarden85** [comment]
Thanks @Grumblezz, working fine now.
