### ISSUE TITLE
Can't notify all devices if any companion app doesn't support notifications

### ISSUE THREAD

**Issue by slevin22** [Grumblezz/Home-Assistant-Notify-Mobile-Companion-App-Devices#14]
Hi,
I have the companion app installed on a tablet that is running a very barebones version of android and does not support notifications via the app. When I try to send a notification to all devices, the tablet interferes giving a "Device not connected to local push notifications" error. Is there any way to exclude a device so that I can dynamically notify all devices?

**Comment by Grumblezz** [comment]
Hi Slevin22, unfortunately HA does have the functionality to check whether an action/service exists for the type of object that you use. 

So for example, of you have an entity ` light.living_room `  then HA can't inform you which actions are available for it... 
This same principle also applies to the fact that you can't validate if the action/service is there or not... 

So this means that there are a few option:
- create another script (I can provide an example if you are interested), that you first run, which outputs the correct devices, based on various parameters. Then that script becomes the input of the devices for this script
- Select the correct devices that support the notification feature in the 'Notify Devices' parameter
- Expand this script with an 'Exclude devices' parameter. Feel free to send a Pull Request.
- Expand this script to include the option: 'continue_on_error: true' [click here for more info](https://www.home-assistant.io/docs/scripts/#continuing-on-error)

**Comment by Grumblezz** [comment]
@slevin22 Have a look at these [updates](https://github.com/Grumblezz/Home-Assistant-Notify-Mobile-Companion-App-Devices/tree/14-cant-notify-all-devices-if-any-companion-app-doesnt-support-notifications) and let me know if that works for you

**Comment by slevin22** [comment]
Those updates look great! Thank you :) I really appreciate your work on this.
